const digest = $input.first().json.response;
const jobs = $('Prepare Digest Prompt').first().json.jobs;

const today = new Date().toLocaleDateString('en-CA', {
  weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
});

// Build a simple HTML email
const rankedJobs = [...jobs].sort((a, b) => b.match_score - a.match_score);
const strongMatches = rankedJobs.filter(j => j.match_score >= 7);
const topJobs = (strongMatches.length >= 3 ? strongMatches : rankedJobs.slice(0, 3))
    .map(j =>
        `<tr>
        <td style="padding:8px;border-bottom:1px solid #eee;">
            <strong>${j.title}</strong><br/>
            ${j.company} — ${j.location}<br/>
            <span style="color:#2d7d46;font-weight:bold;">Score: ${j.match_score}/10</span><br/>
            <em>${j.match_reason}</em><br/>
            <a href="${j.apply_link}" style="color:#1a73e8;">Apply Now →</a>
        </td>
        </tr>`
    ).join("");

const html = `
<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;">
  <h1 style="color:#1a1a1a;border-bottom:2px solid #1a73e8;padding-bottom:10px;">
    Job Agent Daily Digest
  </h1>
  <p style="color:#666;font-size:14px;">${today} — ${jobs.length} jobs analyzed</p>

  <div style="background:#f8f9fa;padding:16px;border-radius:8px;margin:16px 0;">
    ${digest.replace(/\n/g, "<br/>")}
  </div>

  ${topJobs ? `
  <h2 style="color:#1a1a1a;">🏆 Top Matches</h2>
  <table style="width:100%;border-collapse:collapse;">${topJobs}</table>
  ` : ""}

  <hr style="margin:24px 0;border:none;border-top:1px solid #eee;"/>
  <p style="color:#999;font-size:12px;">
    Generated by your local Job Board Agent
  </p>
</div>`;

return [{
  json: {
    subject: `Job Digest — ${today} — ${jobs.length} jobs, ${jobs.filter(j => j.match_score >= 7).length} strong matches`,
    html: html
  }
}];